language: generic 
sudo: required
services:
  - docker
  
before_install:
  - docker build -t sreehariii/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sreehariii/docker-react npm run test
